version: "3.9"
services:
  postgres_db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: "appDB"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pgpwd4"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: pg_isready -U user -d appDB
      interval: 1s
      timeout: 2s
      retries: 5
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54326:5432"
    networks:
      - app-network
networks:
  app-network:
    name: app-network
volumes:
  postgres_data:
