// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/asset/": {
            "get": {
                "description": "Получение всех ассетов текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API для работы с ассетами"
                ],
                "summary": "Получение списка ассетов",
                "operationId": "asset-getlist",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer access_token",
                        "description": "Токен доступа для текущего пользователя",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список ассетов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/asset.AssetResponseDTO"
                            }
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/asset/upload/{name}": {
            "post": {
                "description": "Аплоад файла на сервер",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "API для работы с ассетами"
                ],
                "summary": "Upload файла в базу данных",
                "operationId": "asset-upload",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer access_token",
                        "description": "Токен доступа для текущего пользователя",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название файла",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Любое тело запроса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статус",
                        "schema": {
                            "$ref": "#/definitions/v1.uploadResp"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/asset/{name}": {
            "get": {
                "description": "Получение одного файла по его имени",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API для работы с ассетами"
                ],
                "summary": "Получение ассета",
                "operationId": "asset-get",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer access_token",
                        "description": "Токен доступа для текущего пользователя",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название файла",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ассет",
                        "schema": {
                            "$ref": "#/definitions/asset.AssetResponseDTO"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление одного файла по его имени",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API для работы с ассетами"
                ],
                "summary": "Удаление ассета",
                "operationId": "asset-delete",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer access_token",
                        "description": "Токен доступа для текущего пользователя",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название файла",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статус",
                        "schema": {
                            "$ref": "#/definitions/v1.uploadResp"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Авторизация пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API для авторизации пользователей"
                ],
                "summary": "Авторизация пользователя",
                "operationId": "auth-login",
                "parameters": [
                    {
                        "description": "credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен",
                        "schema": {
                            "$ref": "#/definitions/v1.tokenResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "asset.AssetResponseDTO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "auth.AuthDTO": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        },
        "response.Data": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "default": 200
                },
                "data": {},
                "errors": {},
                "meta": {},
                "text": {
                    "type": "string"
                }
            }
        },
        "v1.tokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                }
            }
        },
        "v1.uploadResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TestApp API",
	Description:      "API сервер для тестово задания",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
